name: Deployment to server
on:
  push:
    branches:
    - deployment

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: main
    - name: Setup key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Add Host Key
      run: ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: SSH trust host
      run: for ip in $(dig @1.1.1.1 ${{ secrets.SSH_HOST }} +short); do ssh-keyscan ${{ secrets.SSH_HOST  }},$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
    - name: Make rsync to bot
      rsync -a -e ssh ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:bot/
    - name: Connect and run
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} cd bot && ls -la && python3.8 --version
      
      

